const config = require("../nightwatch/nightwatch.conf.js")
module.exports = {
  "Prototyping apps": function(browser) {
    browser
      .url("http://localhost:8080")
      .waitForElementVisible("body", 1000)
      .waitForElementVisible("button[name=btn-add]", 1000)
      .click("button[name='btn-add']")
      .waitForElementVisible("input.prompt", 1000)
      .setValue('input.prompt', 'IDR')
      .waitForElementVisible("button.search-submit", 1000)
      .click("button.search-submit")
      .pause(1000)
      .waitForElementVisible("button[name=btn-add]", 1000)
      .click("button[name='btn-add']")
      .waitForElementVisible("input.prompt", 1000)
      .setValue('input.prompt', 'MYR')
      .waitForElementVisible("button.search-submit", 1000)
      .click("button.search-submit")
      .pause(1000)
      .waitForElementVisible("button[name=btn-add]", 1000)
      .click("button[name='btn-add']")
      .waitForElementVisible("input.prompt", 1000)
      .setValue('input.prompt', 'JPY')
      .waitForElementVisible("button.search-submit", 1000)
      .click("button.search-submit")
      .pause(1000)
      .waitForElementVisible("button[name=btn-add]", 1000)
      .click("button[name='btn-add']")
      .waitForElementVisible("input.prompt", 1000)
      .setValue('input.prompt', 'EUR')
      .waitForElementVisible("button.search-submit", 1000)
      .click("button.search-submit")
      .pause(1000)
      .waitForElementVisible("button[name=btn-add]", 1000)
      .click("button[name='btn-add']")
      .waitForElementVisible("input.prompt", 1000)
      .setValue('input.prompt', 'CNA')
      .waitForElementVisible("button.search-submit", 1000)
      .click("button.search-submit")
      .pause(3000)
      .end();
  }
};
